services:
  backend:
    build:
      context: ./backend
    container_name: vertiche-backend
    ports:
      - "8000:8000"

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_ENDPOINT: minio:9000

    depends_on:
      - postgres
      - redis
      - minio

    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
        VITE_USE_MOCKS: ${VITE_USE_MOCKS}

    container_name: vertiche-frontend
    ports:
      - "5173:80"

    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: vertiche-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vertiche

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: vertiche-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: vertiche-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data
    networks:
      - app-network

volumes:
  pgdata:
  miniodata:

networks:
  app-network:
    driver: bridge
