"""initial

Revision ID: 11e53d18194c
Revises:
Create Date: 2026-06-10 00:02:07.123519

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11e53d18194c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historial",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("accion", sa.String(length=100), nullable=False),
        sa.Column("entidad", sa.String(length=50), nullable=False),
        sa.Column("entidad_id", sa.String(length=36), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_historial_accion"), "historial", ["accion"], unique=False)
    op.create_index(
        op.f("ix_historial_entidad"), "historial", ["entidad"], unique=False
    )
    op.create_index(
        op.f("ix_historial_entidad_id"), "historial", ["entidad_id"], unique=False
    )
    op.create_table(
        "tiendas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("estado", sa.String(length=100), nullable=False),
        sa.Column("municipio", sa.String(length=255), nullable=False),
        sa.Column("direccion", sa.Text(), nullable=False),
        sa.Column("marcas", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("cumplimiento", sa.Float(), nullable=False),
        sa.Column("estado_cumplimiento", sa.String(length=30), nullable=False),
        sa.Column("total_tramites", sa.Integer(), nullable=False),
        sa.Column("tramites_vencidos", sa.Integer(), nullable=False),
        sa.Column("tramites_por_vencer", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tiendas_estado"), "tiendas", ["estado"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("rol", sa.String(length=20), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_table(
        "documentos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("nombre_archivo", sa.String(length=500), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("estado_ocr", sa.String(length=30), nullable=False),
        sa.Column(
            "datos_extraidos", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("requiere_revision_manual", sa.Boolean(), nullable=False),
        sa.Column("cargado_por", sa.String(length=36), nullable=False),
        sa.Column("tienda_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["cargado_por"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tienda_id"], ["tiendas.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documentos_tienda_id"), "documentos", ["tienda_id"], unique=False
    )
    op.create_table(
        "tramites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tienda_id", sa.String(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("estado", sa.String(length=40), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=True),
        sa.Column("es_permanente", sa.Boolean(), nullable=False),
        sa.Column("es_recurrente", sa.Boolean(), nullable=False),
        sa.Column("periodo_recurrencia", sa.String(length=50), nullable=True),
        sa.Column("asignado_a", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["asignado_a"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tienda_id"], ["tiendas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tramites_estado"), "tramites", ["estado"], unique=False)
    op.create_index(
        op.f("ix_tramites_tienda_id"), "tramites", ["tienda_id"], unique=False
    )
    op.create_table(
        "usuario_tiendas",
        sa.Column("usuario_id", sa.String(length=36), nullable=False),
        sa.Column("tienda_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["tienda_id"], ["tiendas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("usuario_id", "tienda_id"),
    )
    op.create_table(
        "alertas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("severidad", sa.String(length=20), nullable=False),
        sa.Column("tienda_id", sa.String(length=36), nullable=False),
        sa.Column("tramite_id", sa.String(length=36), nullable=True),
        sa.Column("documento_id", sa.String(length=36), nullable=True),
        sa.Column("mensaje", sa.Text(), nullable=False),
        sa.Column(
            "fecha_generacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("silenciada", sa.Boolean(), nullable=False),
        sa.Column("silenciada_hasta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("silenciada_por", sa.String(length=36), nullable=True),
        sa.Column("resuelta", sa.Boolean(), nullable=False),
        sa.Column("fecha_resolucion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resuelta_por", sa.String(length=36), nullable=True),
        sa.Column(
            "notificaciones_enviadas",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["documento_id"], ["documentos.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["resuelta_por"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["silenciada_por"], ["usuarios.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tienda_id"], ["tiendas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tramite_id"], ["tramites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alertas_severidad"), "alertas", ["severidad"], unique=False
    )
    op.create_index(
        op.f("ix_alertas_tienda_id"), "alertas", ["tienda_id"], unique=False
    )
    op.create_index(op.f("ix_alertas_tipo"), "alertas", ["tipo"], unique=False)
    op.create_table(
        "documento_tramites",
        sa.Column("documento_id", sa.String(length=36), nullable=False),
        sa.Column("tramite_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["documento_id"], ["documentos.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tramite_id"], ["tramites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("documento_id", "tramite_id"),
    )
    op.create_table(
        "observaciones",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tramite_id", sa.String(length=36), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("severidad", sa.String(length=20), nullable=False),
        sa.Column(
            "fecha",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tramite_id"], ["tramites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observaciones_tramite_id"),
        "observaciones",
        ["tramite_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observaciones_tramite_id"), table_name="observaciones")
    op.drop_table("observaciones")
    op.drop_table("documento_tramites")
    op.drop_index(op.f("ix_alertas_tipo"), table_name="alertas")
    op.drop_index(op.f("ix_alertas_tienda_id"), table_name="alertas")
    op.drop_index(op.f("ix_alertas_severidad"), table_name="alertas")
    op.drop_table("alertas")
    op.drop_table("usuario_tiendas")
    op.drop_index(op.f("ix_tramites_tienda_id"), table_name="tramites")
    op.drop_index(op.f("ix_tramites_estado"), table_name="tramites")
    op.drop_table("tramites")
    op.drop_index(op.f("ix_documentos_tienda_id"), table_name="documentos")
    op.drop_table("documentos")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_tiendas_estado"), table_name="tiendas")
    op.drop_table("tiendas")
    op.drop_index(op.f("ix_historial_entidad_id"), table_name="historial")
    op.drop_index(op.f("ix_historial_entidad"), table_name="historial")
    op.drop_index(op.f("ix_historial_accion"), table_name="historial")
    op.drop_table("historial")
    # ### end Alembic commands ###
