"""crear reglas_alerta

Revision ID: 32d49c039395
Revises: c2f90a1b63e8
Create Date: 2026-06-10 20:07:48.532248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d49c039395'
down_revision: Union[str, Sequence[str], None] = 'c2f90a1b63e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_alerta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo_regla', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('dias_antes_vencimiento', sa.Integer(), nullable=True),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('aplica_a_estado', sa.String(length=50), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_alerta_codigo_regla'), 'reglas_alerta', ['codigo_regla'], unique=True)
    op.add_column('alertas', sa.Column('regla_id', sa.String(length=36), nullable=True))
    op.add_column('alertas', sa.Column('fecha', sa.Date(), nullable=True))
    op.create_index(op.f('ix_alertas_fecha'), 'alertas', ['fecha'], unique=False)
    op.create_unique_constraint('uix_alerta_idempotency', 'alertas', ['tramite_id', 'regla_id', 'fecha'])
    op.create_foreign_key(None, 'alertas', 'reglas_alerta', ['regla_id'], ['id'], ondelete='SET NULL')
    op.add_column('documentos', sa.Column('categoria', sa.String(length=50), nullable=True))
    op.add_column('documentos', sa.Column('fecha_fin_vigencia', sa.Date(), nullable=True))
    op.add_column('documentos', sa.Column('es_permanente', sa.Boolean(), nullable=False))
    op.add_column('documentos', sa.Column('confianza_extraccion', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'confianza_extraccion')
    op.drop_column('documentos', 'es_permanente')
    op.drop_column('documentos', 'fecha_fin_vigencia')
    op.drop_column('documentos', 'categoria')
    op.drop_constraint(None, 'alertas', type_='foreignkey')
    op.drop_constraint('uix_alerta_idempotency', 'alertas', type_='unique')
    op.drop_index(op.f('ix_alertas_fecha'), table_name='alertas')
    op.drop_column('alertas', 'fecha')
    op.drop_column('alertas', 'regla_id')
    op.drop_index(op.f('ix_reglas_alerta_codigo_regla'), table_name='reglas_alerta')
    op.drop_table('reglas_alerta')
    # ### end Alembic commands ###
