"""rename_url_to_ruta_archivo

Revision ID: bc4866e4f4ca
Revises: 11e53d18194c
Create Date: 2026-06-10 18:18:04.206662

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc4866e4f4ca"
down_revision: str | Sequence[str] | None = "11e53d18194c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("documentos", "url", new_column_name="ruta_archivo")
    op.create_foreign_key(
        None, "historial", "usuarios", ["actor_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "historial", type_="foreignkey")
    op.alter_column("documentos", "ruta_archivo", new_column_name="url")
    # ### end Alembic commands ###
