"""Add OCR fields to Documento

Revision ID: c2f90a1b63e8
Revises: bc4866e4f4ca
Create Date: 2026-06-10 16:30:00.000000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "c2f90a1b63e8"
down_revision = "bc4866e4f4ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documentos", sa.Column("texto_ocr", sa.Text(), nullable=True))
    op.add_column(
        "documentos",
        sa.Column(
            "ocr_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documentos", "ocr_metrics")
    op.drop_column("documentos", "texto_ocr")
    # ### end Alembic commands ###
